<Project>
  <ItemGroup>
    <PackageVersion Include="Kroste.ModManager.PluginContracts" Version="0.2.0" />
    <PackageVersion Include="Avalonia" Version="12.1.0" />
    <PackageVersion Include="CommunityToolkit.Mvvm" Version="8.4.2" />
    <PackageVersion Include="MinVer" Version="7.0.0" />
  </ItemGroup>
</Project>
